# DremelDocs Revolutionary Theory Archive
site_name: DremelDocs Archive
site_url: https://percy-raskova.github.io/dremeldocs
site_author: Percy Raskova
site_description: >-
  A curated archive of revolutionary theory, political analysis,
  and critical discourse from over a decade of philosophical inquiry.

# Repository
repo_url: https://github.com/percy-raskova/dremeldocs
repo_name: dremeldocs

# Use markdown directory for the actual content
docs_dir: markdown

# Theme configuration
theme:
  name: material
  language: en

  # Color scheme - using a more neutral professional scheme
  palette:
    - scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # Typography
  font:
    text: Roboto
    code: Roboto Mono

  # Features
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - toc.follow
    - toc.integrate

  # Icons
  icon:
    logo: material/library
    repo: fontawesome/brands/github

# Plugins with corrected tags configuration
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang:
        - en

  # Tags plugin for Material theme
  - tags:
      enabled: true

  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true

# Extensions
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3

# Navigation - simplified structure
# Individual thread files accessible via theme index pages and search
nav:
  - Home: index.md

  - About:
      - About This Archive: about/index.md
      - Usage Guide: about/usage.md

  - Themes:
      - Overview: themes/index.md
      - Marxism: marxism/index.md
      - Political Economy: economy/index.md
      - Organizing: organizing/index.md
      - COVID: covid/index.md
      - Fascism: fascism/index.md
      - Culture: culture/index.md
      - Imperialism: imperialism/index.md
      - Dialectics: dialectics/index.md
      - Uncategorized: uncategorized/index.md

  - Analysis:
      - Overview: analysis/index.md

  - Tags: tags.md

# Suppress warnings for thread files not in nav (they're accessible via theme pages)
not_in_nav: |
  /INSURRECTION.md
  /covid/*.md
  /marxism/*.md
  /economy/*.md
  /organizing/*.md
  /fascism/*.md
  /culture/*.md
  /imperialism/*.md
  /dialectics/*.md
  /uncategorized/*.md
  !/*/index.md

# Extra configuration
extra:
  # Disable version checking to prevent 404 errors
  version:
    provider: none

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/percy-raskova
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/BmoreOrganized

extra_css:
  - stylesheets/extra.css
  - stylesheets/tags.css