# MkDocs configuration for @BmoreOrganized's Twitter Archive

site_name: Philosophy & Politics - Ms. Dremel's Archive
site_description: Philosophical and political threads from @BmoreOrganized's Twitter archive
site_author: '@BmoreOrganized'
site_url: https://example.com  # Update with actual URL

# Important: Use markdown/ instead of docs/
docs_dir: markdown
site_dir: site

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

plugins:
  - search
  - tags

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Navigation structure (to be populated after classification)
nav:
  - Home: index.md
  - Philosophy: philosophy/
  - Politics: politics/
  - Both: both/
  - By Theme: themes/
  - About:
    - AI Collaboration: about/ai-collaboration.md

# Custom CSS
extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/BmoreOrganized
  generator: false  # Don't show "Made with Material for MkDocs"